remote_theme: realone233/line
title: Realone in the Box
markdown: kramdown
logo: /assets/img/logo.png
extend: <div class="box"><div class="fold"><a href="https://realone233.github.io/pages/index.html">Pages| View our posts.</a><br /><a href="https://realone233.github.io/flags/index.html">Flags| Try something interesting.</a><br /><a href="https://creativecommons.org/licenses/by-sa/4.0">Licensed under CC BY-SA 4.0</a></div></div>
