remote_theme: realone233/line
title: Realone in the Box
markdown: kramdown
logo: /assets/img/logo.png
extend: <div class="list-box"><a href="https://realone233.github.io/pages/index.html"><div class="list">Pages| View our posts.</div></a><br /><a href="https://realone233.github.io/flags/index.html"><div class="list">Flags| Try something interesting.</div></a><br /><a href="https://creativecommons.org/licenses/by-sa/4.0"><div class="list">Licensed under CC BY-SA 4.0</div></a></div>
